### ISSUE TITLE
default footer still lists Lightbend copyright

### ISSUE THREAD

**Issue by raboof** [apache/pekko-sbt-paradox#136]
The default footer still seems to be

```
    Global / pekkoParadoxCopyright :=
      """Copyright © 2011-2022 <a href="https://www.lightbend.com/">Lightbend, Inc</a>.
        | Apache Pekko, Pekko, and its feather logo are trademarks of The Apache Software Foundation.""".stripMargin,
```

Should that still be there like that?

**Comment by pjfanning** [comment]
This is covered by https://issues.apache.org/jira/browse/LEGAL-634

My reading is that we need a Lightbend copyright and nobody cares too much about adding an ASF copyright.
